export const redirects: Record<string, string> = {
  // Legacy section roots
  '/methods': '/ai-analytics/',
  '/methods/': '/ai-analytics/',
  '/frameworks': '/ai-analytics/',
  '/frameworks/': '/ai-analytics/',
  '/pipelines': '/ai-analytics/',
  '/pipelines/': '/ai-analytics/',
  '/tools': '/ai-analytics/',
  '/tools/': '/ai-analytics/',
  '/projects': '/builds/',
  '/projects/': '/builds/',

  // AI analytics pages
  '/methods/ai-metascientist': '/ai-analytics/ai-metascientist',
  '/methods/ai-metascientist/': '/ai-analytics/ai-metascientist/',
  '/writing/ai-metascientist': '/ai-analytics/ai-metascientist',
  '/writing/ai-metascientist/': '/ai-analytics/ai-metascientist/',
  '/frameworks/biblioflow': '/ai-analytics/biblioflow',
  '/frameworks/biblioflow/': '/ai-analytics/biblioflow/',
  '/writing/biblioflow': '/ai-analytics/biblioflow',
  '/writing/biblioflow/': '/ai-analytics/biblioflow/',
  '/frameworks/grid-plus': '/ai-analytics/grid-plus',
  '/frameworks/grid-plus/': '/ai-analytics/grid-plus/',
  '/pipelines/grid-plus': '/ai-analytics/grid-plus',
  '/pipelines/grid-plus/': '/ai-analytics/grid-plus/',
  '/methods/journalscape': '/ai-analytics/journalscape',
  '/methods/journalscape/': '/ai-analytics/journalscape/',
  '/pipelines/journalscape': '/ai-analytics/journalscape',
  '/pipelines/journalscape/': '/ai-analytics/journalscape/',
  '/tools/biblioscope': '/ai-analytics/biblioscope',
  '/tools/biblioscope/': '/ai-analytics/biblioscope/',
  '/pipelines/biblioscope': '/ai-analytics/biblioscope',
  '/pipelines/biblioscope/': '/ai-analytics/biblioscope/',
  '/frameworks/dimquery': '/ai-analytics/dimquery',
  '/frameworks/dimquery/': '/ai-analytics/dimquery/',
  '/tools/dimquery': '/ai-analytics/dimquery',
  '/tools/dimquery/': '/ai-analytics/dimquery/',
  '/projects/claude-projects-workflows': '/ai-analytics/corpus-builder',
  '/projects/claude-projects-workflows/': '/ai-analytics/corpus-builder/',
  '/tools/claude-projects-workflows': '/ai-analytics/corpus-builder',
  '/tools/claude-projects-workflows/': '/ai-analytics/corpus-builder/',

  // Evaluation
  '/tools/ava': '/evaluation/av-va',
  '/tools/ava/': '/evaluation/av-va/',
  '/tools/av-va': '/evaluation/av-va',
  '/tools/av-va/': '/evaluation/av-va/',

  // Builds
  '/projects/loom': '/builds/loom',
  '/projects/loom/': '/builds/loom/',
  '/tools/loom': '/builds/loom',
  '/tools/loom/': '/builds/loom/',
  '/projects/children-voice-assistant': '/builds/children-voice-assistant',
  '/projects/children-voice-assistant/': '/builds/children-voice-assistant/',
  '/tools/children-voice-assistant': '/builds/children-voice-assistant',
  '/tools/children-voice-assistant/': '/builds/children-voice-assistant/',

  // Writing
  '/projects/bumped-stacked-bar': '/writing/tufte-extensions',
  '/projects/bumped-stacked-bar/': '/writing/tufte-extensions/',
  '/projects/interviewing-yourself': '/writing/interviewing-yourself',
  '/projects/interviewing-yourself/': '/writing/interviewing-yourself/',

  // About / contact
  '/contact': '/cv',
  '/contact/': '/cv/',
  '/about/contact': '/cv',
  '/about/contact/': '/cv/',
  '/about/cv': '/cv',
  '/about/cv/': '/cv/',
}
